system:
  distributed_backend: nccl
  reset_position_ids: False
  reset_attention_mask: False
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  use_distributed_optimizer: True
  precision:
    fp16: True
    bf16: False
  logging:
    log_interval: 10
    tensorboard_log_interval: 10
    tensorboard_dir: ./output/logs
  checkpoint:
    save: ./output/ckpts
    load: ./output/ckpts
    save_interval: 500

model:
  num_layers: 32
  hidden_size: 2560
  num_attention_heads: 8
  seq_length: 512
  max_position_embeddings: 512
  init_method_std: 0.02
  clip_grad: 1.0
  micro_batch_size: 2
  global_batch_size: 8
  train_iters: 1000
  eval_iters: 2
  eval_interval: 100
  seed: 1234

  optimizer:
    weight_decay: 0.01
    adam_beta1: 0.9
    adam_beta2: 0.95
    lr_scheduler:
      lr: 1.0e-4
      min_lr: 1.0e-5
      lr_warmup_fraction: 0.01
      lr_decay_style: cosine

data:
  data_path: ./data/demo
  split: "16,3,1"
  tokenizer:
    vocab_file: ./data/gpt2-tokenizer/gpt2-vocab.json
    merge_file: ./data/gpt2-tokenizer/gpt2-merges.txt
